### ISSUE TITLE
Publish repositories fails bc gpg key creation and key ids aren't tracked correctly

### ISSUE THREAD

**Issue by timblaktu** [idealista/aptly-role#7]
When running your role on a fresh Debian Buster machine (after working through several earlier errors), I'm now getting the below error in the "Publish repositories" task:

```
TASK [aptly : APTLY | Publish repositories] **************************************************************************************************failed: [aptly] (item=biamp-stretch) => changed=true                                                                                            ansible_loop_var: item
  cmd:                                                                                                                                          - aptly
  - publish
  - repo                                                                                                                                        - -config=/etc/aptly.conf
  - -component=main
  - -gpg-key=pub
  - biamp-stretch                                                                                                                               - biamp-stretch                                                                                                                               delta: '0:00:00.033917'
  end: '2020-11-10 10:38:10.176240'
  item: biamp-stretch                                                                                                                           msg: non-zero return code                                                                                                                     rc: 1
  start: '2020-11-10 10:38:10.142323'
  stderr: |-                                                                                                                                      gpg: skipped "pub": No secret key
    gpg: signing failed: No secret key
    ERROR: unable to publish: unable to detached sign file: exit status 2                                                                       stderr_lines: <omitted>
  stdout: |-
    Warning: publishing from empty source, architectures list should be complete, it can't be changed after publishing (use -architectures flag)
    Loading packages...
    Generating metadata files and linking package files...                                                                                        Finalizing metadata files...
    Signing file 'Release' with gpg, please enter your passphrase when prompted:
  stdout_lines: <omitted>                                                                                                                     ...ignoring
```

I believe the problem (gpg: skipped "pub": No secret key) is that the gpg key id used in the `aptly publish repo` command ("pub") isn't the key id you should be using. This key id is found from taking the last one reported from your `gpg --list-keys` command in tasks/config.yml: 

```
gpg --list-keys | grep 'pub ' | tail -1 | sed 's/pub   2048D\///g' | cut -d' ' -f1
```

Aside from the gpgkey generation and usage not working in this role, I'm genuinely confused about what you're trying to accomplish by grabbing the last key from the list. Seems to me that  you'd want to use the one associated with the email addr..

**Comment by timblaktu** [comment]
My playbook had separately installed gpg key, which may have violated some assumption you were making. Anywya, I comment out my gpg installation from the playbook, reverted to a fresh Buster machine and reran, and then got this:

```
TASK [aptly : APTLY | Generate gpg keys] *****************************************************************************************************fatal: [aptly]: FAILED! => changed=true
  cmd:
  - gpg
  - --batch
  - --gen-key
  - /tmp/gpg
  delta: '0:00:01.013251'
  end: '2020-11-10 11:44:20.820513'
  msg: non-zero return code
  rc: 2
  start: '2020-11-10 11:44:19.807262'
  stderr: |-
    gpg: WARNING: some OpenPGP programs can't handle a DSA key with this digest size
    gpg: agent_genkey failed: Inappropriate ioctl for device
    gpg: key generation failed: Inappropriate ioctl for device
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
This is resolved by [setting GPG_TTY env var](https://unix.stackexchange.com/questions/257061/gentoo-linux-gpg-encrypts-properly-a-file-passed-through-parameter-but-throws-i/257065#257065).
